version: '3'
services:

  redis-stack:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8182:8001

  application-client:
    container_name: application-client
    build:
      context: ./application/client
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - APPLICATION_HOST=application-server
      - APPPLICATION_PORT=8001
    depends_on:
      - application-server

  application-server:
    container_name: application-server
    build:
      context: ./application/server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis-stack

  broker-client:
    build:
      context: ./broker/client
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  broker-server:
    build:
      context: ./broker/server
      dockerfile: Dockerfile
    ports:
      - 3001:3001

  fidoserver:
    build:
      context: ./fidoserver
      dockerfile: Dockerfile
    ports:
      - 8181:8181